import { StyleSheet, StatusBar, Platform } from 'react-native';

export default StyleSheet.create({
      homeContainer: {
  flex: 1,
  backgroundColor: '#F5F7FA',
  justifyContent: 'space-between',
  alignItems: 'center', 
  paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight + 10 : 50, 
},
container: {
  flex: 1, 
  width: '100%',
},
boxContainer: {
    marginTop: 20,
    width: '85%',
    height: 150,
    alignItems: 'center',
    backgroundColor: 'black',
    justifyContent: 'center',
    borderRadius: 40,
  },
    navigationContainer: {
  flexDirection: 'row',
  height: 80,
  backgroundColor: '#FFFFFF',
  borderTopWidth: 1,
  borderTopColor: '#EEE',
  justifyContent: 'space-around',
  alignItems: 'center',
  paddingBottom: 20,
  width: '100%',
},
    navButton: {
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
    },
    noteContainer: {
    padding: 15,
    marginVertical: 8,
    marginHorizontal: 16,
    backgroundColor: '#fff',
    borderRadius: 10,
    elevation: 3,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
  },
  selectedNote: {
    backgroundColor: '#f0f0f0',
    borderColor: '#4A90E2',
    borderWidth: 1,
  },
  noteText: {
    fontSize: 16,
    color: '#333',
  },
  grayedText: {
    color: '#aaa',
    textDecorationLine: 'line-through',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent:{
    width: '80%',
    height: '80%',
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
  },
  addButton: {
    marginTop: 20,
    width: '85%',
    height: 150,
    alignItems: 'center',
    backgroundColor: 'black',
    justifyContent: 'center',
    borderRadius: 40, 
  },
  textInput: {
    width: '100%',
  fontSize: 18,
  paddingVertical: 10,
  backgroundColor: 'transparent',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    marginBottom: 20,
  },
  notesContainer: {
    flex: 1,
    width: '100%',
    paddingHorizontal: 20,
    marginTop: 20,
    borderRadius: 40,
  },
  noteCard: {
  backgroundColor: '#1a1a1a',
  padding: 20,
  borderRadius: 15,
  marginBottom: 12,
  elevation: 3,
  shadowColor: '#000',
  shadowOffset: { width: 0, height: 2 },
  shadowOpacity: 0.3,
  shadowRadius: 4,
},
noteTextPreview: {
  color: '#ffffff',
  fontSize: 16,
  fontWeight: '500',
  marginBottom: 8,
},
noteDate: {
  color: '#666',
  fontSize: 12,
  textAlign: 'right',
},
fullNoteText: {
  fontSize: 18,
  lineHeight: 26,
  color: '#333',
},
scrollNote: {
  maxHeight: 400,
  marginBottom: 20,
},
noteHeader: {
  flexDirection: 'row',
  justifyContent: 'flex-end',
},
});